frr version 8.5.2
frr defaults traditional
hostname leaf02
log stdout
!
interface lo
 ip address 10.0.0.12/32
 ip ospf area 0.0.0.0
!
interface eth1
 description P2P_SPINE01
 ip address 10.1.2.1/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf bfd
!
interface eth2
 description P2P_SPINE02
 ip address 10.1.2.3/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf bfd
!
interface eth3
 description LAN_CLIENT_B
 ip address 192.168.20.1/24
!
router ospf
 ospf router-id 10.0.0.12
 timers throttle spf 10 50 200
!
router bgp 65012
 bgp router-id 10.0.0.12
 no bgp ebgp-requires-policy
 neighbor SPINES peer-group
 neighbor SPINES remote-as 65001
 neighbor SPINES bfd
 neighbor 10.1.2.0 peer-group SPINES
 neighbor 10.1.2.2 peer-group SPINES
 !
 address-family ipv4 unicast
  network 192.168.20.0/24
  neighbor SPINES activate
  maximum-paths 2
 exit-address-family
!
bfd
 peer 10.1.2.0
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
 peer 10.1.2.2
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
line vty
!
