frr version 8.5.2
frr defaults traditional
hostname spine01
log stdout
!
interface lo
 ip address 10.0.0.1/32
 ip ospf area 0.0.0.0
!
interface eth1
 description P2P_LEAF01
 ip address 10.1.1.0/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf bfd
!
interface eth2
 description P2P_LEAF02
 ip address 10.1.2.0/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf bfd
!
interface eth3
 description P2P_SPINE02
 ip address 10.255.0.0/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf bfd
!
router ospf
 ospf router-id 10.0.0.1
 timers throttle spf 10 50 200
!
router bgp 65001
 bgp router-id 10.0.0.1
 no bgp ebgp-requires-policy
 neighbor 10.1.1.1 remote-as 65011
 neighbor 10.1.1.1 bfd
 neighbor 10.1.2.1 remote-as 65012
 neighbor 10.1.2.1 bfd
 !
 address-family ipv4 unicast
  neighbor 10.1.1.1 activate
  neighbor 10.1.2.1 activate
  maximum-paths 2
 exit-address-family
!
bfd
 peer 10.1.1.1
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
 peer 10.1.2.1
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
 peer 10.255.0.1
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
line vty
!
